version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - maintenance

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - maintenance

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    labels:
      - maintenance
